import xml.etree.ElementTree as ET
from datetime import date
from decimal import Decimal
from xml.dom import minidom

from src.models.parsed_invoice import ParsedInvoice
from src.models.vendor_config import TargetXMLConfig, TargetXMLElement
from src.models.xml_types import (
    PohodaFaktura,
    PohodaFirma,
    PohodaPolozka,
    PohodaSouhrnDPH,
)


class InvoiceToXMLExporter:
    """Converts ParsedInvoice objects to Pohoda models and target XML."""

    @staticmethod
    def export(invoice: ParsedInvoice) -> PohodaFaktura:
        """Convert ParsedInvoice to PohodaFaktura XML type.

        Args:
            invoice: Parsed invoice data

        Returns:
            PohodaFaktura ready for XML serialization
        """
        return PohodaFaktura(
            Doklad=None,  # Auto-generated by Pohoda
            PrijatDokl=invoice.received_invoice_number,
            Vystaveno=invoice.issue_date,
            PlnenoDPH=invoice.supply_date,
            Doruceno=max(invoice.issue_date, invoice.supply_date),
            Splatno=invoice.due_date,
            VarSymbol=invoice.variable_symbol or invoice.received_invoice_number,
            KonstSym=invoice.constant_symbol,
            Popis=invoice.description,
            Druh=InvoiceToXMLExporter._convert_invoice_type(invoice),
            SouhrnDPH=InvoiceToXMLExporter._convert_vat_breakdown(invoice),
            DodOdb=InvoiceToXMLExporter._convert_supplier(invoice),
            SeznamPolozek=InvoiceToXMLExporter._convert_line_items(invoice),
        )

    @staticmethod
    def export_target_xml(
        invoices: PohodaFaktura | list[PohodaFaktura],
        config: TargetXMLConfig,
    ) -> str:
        """Serialize one or more Pohoda invoices into the configured target XML."""
        invoice_list = invoices if isinstance(invoices, list) else [invoices]
        root = ET.Element(config.root_tag, config.root_attributes)

        for template in config.body:
            InvoiceToXMLExporter._append_template_element(
                parent=root,
                template=template,
                invoices=invoice_list,
                current_invoice=None,
            )

        xml_bytes = ET.tostring(root, encoding="utf-8")
        pretty_xml = minidom.parseString(xml_bytes).toprettyxml(
            indent="    ",
            encoding="UTF-8",
        )
        return pretty_xml.decode("utf-8")

    @staticmethod
    def _convert_invoice_type(invoice: ParsedInvoice) -> str:
        """Convert invoice type to Pohoda format.

        Args:
            invoice: Parsed invoice data

        Returns:
            Single character type code: N=normal, P=proforma
        """
        if invoice.is_credit_note:
            return "D"
        return {"normal": "N", "proforma": "P", "credit_note": "D"}.get(
            invoice.invoice_type, "N"
        )

    @staticmethod
    def _convert_supplier(invoice: ParsedInvoice) -> PohodaFirma:
        """Convert supplier information to Pohoda format.

        Args:
            invoice: Parsed invoice data

        Returns:
            PohodaFirma with supplier information
        """
        supplier = invoice.supplier
        return PohodaFirma(
            Nazev=supplier.name,
            IC=supplier.ic,
            DIC=supplier.dic,
            Ulice=supplier.street,
            Misto=supplier.city,
            PSC=supplier.zip,
            Stat=supplier.country,
        )

    @staticmethod
    def _convert_vat_breakdown(invoice: ParsedInvoice) -> PohodaSouhrnDPH:
        """Convert VAT breakdown to Pohoda format.

        Maps VAT rates to Pohoda fields:
        - 10%, 12%, 15% -> Zaklad1/DPH1 (reduced rate bucket)
        - 21% -> Zaklad2/DPH2 (standard rate)
        - 0% -> Zaklad3/DPH3 (zero rate)

        Args:
            invoice: Parsed invoice data

        Returns:
            PohodaSouhrnDPH with VAT breakdown
        """
        vat_data = {
            "Zaklad1": None,
            "DPH1": None,
            "Zaklad2": None,
            "DPH2": None,
            "Zaklad3": None,
            "DPH3": None,
            "ZakladSniz": None,
            "DPHSniz": None,
            "ZakladZakl": None,
            "DPHZakl": None,
        }

        for vat_breakdown in invoice.vat_breakdowns:
            if vat_breakdown.rate in {
                Decimal("0.10"),
                Decimal("0.12"),
                Decimal("0.15"),
            }:
                vat_data["Zaklad1"] = (vat_data["Zaklad1"] or Decimal("0")) + vat_breakdown.base
                vat_data["DPH1"] = (vat_data["DPH1"] or Decimal("0")) + vat_breakdown.amount
                vat_data["ZakladSniz"] = (vat_data["ZakladSniz"] or Decimal("0")) + vat_breakdown.base
                vat_data["DPHSniz"] = (vat_data["DPHSniz"] or Decimal("0")) + vat_breakdown.amount
            elif vat_breakdown.rate == Decimal("0.21"):
                vat_data["Zaklad2"] = vat_breakdown.base
                vat_data["DPH2"] = vat_breakdown.amount
                vat_data["ZakladZakl"] = vat_breakdown.base
                vat_data["DPHZakl"] = vat_breakdown.amount
            elif vat_breakdown.rate == Decimal("0.00"):
                vat_data["Zaklad3"] = vat_breakdown.base
                vat_data["DPH3"] = vat_breakdown.amount

        return PohodaSouhrnDPH(**vat_data)

    @staticmethod
    def _convert_line_items(invoice: ParsedInvoice) -> list[PohodaPolozka] | None:
        """Convert line items to Pohoda format.

        Args:
            invoice: Parsed invoice data

        Returns:
            List of PohodaPolozka or None if no line items
        """
        if not invoice.line_items:
            return None

        pohoda_items = []
        for item in invoice.line_items:
            # Convert VAT rate from decimal (0.21) to percentage (21.0)
            vat_percentage = (item.vat_rate * Decimal("100")).quantize(Decimal("1"))

            pohoda_item = PohodaPolozka(
                Popis=item.description[:90],  # Truncate to max length
                PocetMJ=item.quantity,
                Cena=item.unit_price,
                SazbaDPH=vat_percentage,
                CenaTyp=0,  # 0 = price without VAT
                MJ=item.unit,
            )
            pohoda_items.append(pohoda_item)

        return pohoda_items

    @staticmethod
    def _append_template_element(
        parent: ET.Element,
        template: TargetXMLElement,
        invoices: list[PohodaFaktura],
        current_invoice: PohodaFaktura | None,
    ) -> None:
        """Append a configured XML element and its descendants."""
        if template.repeat_for_each_invoice:
            for invoice in invoices:
                element = ET.SubElement(parent, template.tag, template.attributes)
                InvoiceToXMLExporter._populate_template_element(
                    element=element,
                    template=template,
                    invoices=invoices,
                    current_invoice=invoice,
                )
            return

        element = ET.SubElement(parent, template.tag, template.attributes)
        InvoiceToXMLExporter._populate_template_element(
            element=element,
            template=template,
            invoices=invoices,
            current_invoice=current_invoice,
        )

    @staticmethod
    def _populate_template_element(
        element: ET.Element,
        template: TargetXMLElement,
        invoices: list[PohodaFaktura],
        current_invoice: PohodaFaktura | None,
    ) -> None:
        """Populate a configured XML element with static or dynamic content."""
        if template.dynamic_field is not None:
            if current_invoice is None:
                raise ValueError(
                    f"Dynamic field '{template.dynamic_field}' requires an invoice context"
                )
            element.text = InvoiceToXMLExporter._resolve_dynamic_field(
                template.dynamic_field,
                current_invoice,
            )
        elif template.text is not None:
            element.text = template.text

        for child in template.children:
            InvoiceToXMLExporter._append_template_element(
                parent=element,
                template=child,
                invoices=invoices,
                current_invoice=current_invoice,
            )

    @staticmethod
    def _resolve_dynamic_field(field_name: str, invoice: PohodaFaktura) -> str:
        """Resolve a configured dynamic field name to a string XML value."""
        souhrn_dph = invoice.SouhrnDPH
        dynamic_values = {
            "Vystaveno": InvoiceToXMLExporter._format_date(invoice.Vystaveno),
            "PlnenoDPH": InvoiceToXMLExporter._format_date(invoice.PlnenoDPH),
            "Doruceno": InvoiceToXMLExporter._format_date(
                max(invoice.Vystaveno, invoice.PlnenoDPH)
            ),
            "Splatno": InvoiceToXMLExporter._format_date(invoice.Splatno),
            "VarSymbol": invoice.VarSymbol or invoice.PrijatDokl or "",
            "PrijatDokl": invoice.PrijatDokl or "",
            "Proplatit": InvoiceToXMLExporter._format_decimal(
                InvoiceToXMLExporter._calculate_total(invoice)
            ),
            "Zaklad0": InvoiceToXMLExporter._format_decimal(souhrn_dph.Zaklad3),
            "Zaklad5": InvoiceToXMLExporter._format_decimal(souhrn_dph.Zaklad1),
            "Zaklad22": InvoiceToXMLExporter._format_decimal(souhrn_dph.Zaklad2),
            "DPH5": InvoiceToXMLExporter._format_decimal(souhrn_dph.DPH1),
            "DPH22": InvoiceToXMLExporter._format_decimal(souhrn_dph.DPH2),
            "Celkem": InvoiceToXMLExporter._format_decimal(
                InvoiceToXMLExporter._calculate_total(invoice)
            ),
        }

        if field_name not in dynamic_values:
            raise ValueError(f"Unsupported dynamic field '{field_name}'")

        return dynamic_values[field_name]

    @staticmethod
    def _calculate_total(invoice: PohodaFaktura) -> Decimal:
        """Calculate total amount from the VAT summary without double-counting aliases."""
        souhrn_dph = invoice.SouhrnDPH
        return sum(
            (
                souhrn_dph.Zaklad1 or Decimal("0"),
                souhrn_dph.DPH1 or Decimal("0"),
                souhrn_dph.Zaklad2 or Decimal("0"),
                souhrn_dph.DPH2 or Decimal("0"),
                souhrn_dph.Zaklad3 or Decimal("0"),
                souhrn_dph.DPH3 or Decimal("0"),
            ),
            start=Decimal("0"),
        )

    @staticmethod
    def _format_date(value: date | None) -> str:
        """Format a date value for XML output."""
        if value is None:
            return ""
        return value.isoformat()

    @staticmethod
    def _format_decimal(value: Decimal | None) -> str:
        """Format decimal values without unnecessary trailing zeros."""
        if value is None:
            return "0"

        normalized = format(value.normalize(), "f")
        if "." not in normalized:
            return normalized
        trimmed = normalized.rstrip("0").rstrip(".")
        return trimmed or "0"
