root_tag: "MoneyData"
root_attributes:
  ICAgendy: "71004378"
  KodAgendy: ""
  HospRokOd: "2026-01-01"
  HospRokDo: "2026-12-31"
  description: "faktury přijaté a vydané"
  ExpZkratka: "_FP+FV"
  JazykVerze: "CZ"
  VyberZaznamu: "0"
invoice_defaults:
  Rada: "2rr"
  CisRada: "19"
  Popis: "zboží"
  KodDPH: "19Ř40,41"
  Ucet: "KB"
  Druh: "N"
  Dobropis: "0"
  Uhrada: "převodem"
  PredKontac: "PF001"
  ZpVypDPH: "1"
  SazbaDPH1: "12"
  SazbaDPH2: "21"
  Vyuctovano: "0"
  Typ: "FP"
  PriUhrZbyv: "0"
  ValutyProp: "0"
  SumZaloha: "0"
  SumZalohaC: "0"
  DopravTuz: "0"
  DopravZahr: "0"
  Sleva: "0"
my_company:
  tag: "MojeFirma"
  children:
    - tag: "Nazev"
      text: "Mgr. Ivana Kantková"
    - tag: "Adresa"
      children:
        - tag: "Ulice"
          text: "Zahradní 1"
        - tag: "Misto"
          text: "Hodonín"
        - tag: "PSC"
          text: "69501"
        - tag: "Stat"
          text: "Česká republika"
        - tag: "KodStatu"
          text: "CZ"
    - tag: "ObchNazev"
      text: "Mgr. Ivana Kantková"
    - tag: "ObchAdresa"
      children:
        - tag: "Ulice"
          text: "Zahradní 1"
        - tag: "Misto"
          text: "Hodonín"
        - tag: "PSC"
          text: "69501"
        - tag: "Stat"
          text: "Česká republika"
        - tag: "KodStatu"
          text: "CZ"
    - tag: "Tel"
      children:
        - tag: "Pred"
          text: ""
        - tag: "Cislo"
          text: ""
        - tag: "Klap"
          text: ""
    - tag: "Fax"
      children:
        - tag: "Pred"
          text: ""
        - tag: "Cislo"
          text: ""
        - tag: "Klap"
          text: ""
    - tag: "Mobil"
      children:
        - tag: "Pred"
          text: ""
        - tag: "Cislo"
          text: "776193921"
    - tag: "EMail"
      text: "lekarnaprimula@seznam.cz"
    - tag: "WWW"
      text: ""
    - tag: "ICO"
      text: "71004378"
    - tag: "DIC"
      text: "CZ6854146574"
    - tag: "Banka"
      text: "Komerční banka, a.s."
    - tag: "Ucet"
      text: "86-2426130207"
    - tag: "KodBanky"
      text: "0100"
    - tag: "KodPartn"
      text: ""
    - tag: "FyzOsoba"
      text: "1"
    - tag: "SpisovaZnacka"
      text: "OŽU/14639/06\n                    ev.č.370602-36271\n                    Hodonín"
    - tag: "MenaSymb"
      text: "Kč"
    - tag: "MenaKod"
      text: "CZK"